// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Served from the root of how-to-fl.github.io, so no `base` path is needed.
// If a custom domain is added later, only `site` changes — nothing else.
export default defineConfig({
	site: 'https://how-to-fl.github.io',
	integrations: [
		starlight({
			title: 'How to FL',
			description:
				'Everything we wish someone had told us before we landed in Beijing. Written by us, for you.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/how-to-fl/how-to-fl.github.io' },
			],
			// Every font and icon must be served from our own origin — see CONTRIBUTING.md.
			// Nothing here may reference a CDN, Google Fonts, or raw.githubusercontent.com.
			customCss: ['./src/styles/fonts.css', './src/styles/custom.css'],
			head: [
				{
					tag: 'link',
					attrs: {
						rel: 'preload',
						as: 'font',
						type: 'font/woff2',
						crossorigin: 'anonymous',
						href: '/fonts/bodoni-moda-latin-normal.woff2',
					},
				},
				{ tag: 'meta', attrs: { name: 'theme-color', content: '#8e1b2c' } },
			],
			components: {
				// Adds JSON-LD + Open Graph image on top of Starlight's head.
				Head: './src/components/Head.astro',
				// The seal + wordmark in the header.
				SiteTitle: './src/components/SiteTitle.astro',
				// Adds the "last checked" line under every page title.
				PageTitle: './src/components/PageTitle.astro',
			},
			// Three categories, plus miscellaneous, plus the standalone tools.
			// Category contents are autogenerated from their directory, so a
			// contributor who adds a Markdown file gets it in the nav for free.
			// Note: as of Starlight 0.39 `autogenerate` must sit inside `items`.
			sidebar: [
				{ label: 'How this guide works', slug: 'how-to-use-this' },
				{ label: 'The map', slug: 'map' },
				{ label: "When something's gone wrong", slug: 'emergency' },
				{
					label: '1 · China — landing & first 72h',
					items: [{ autogenerate: { directory: 'china' } }],
				},
				{
					label: '2 · PKU & academics',
					items: [{ autogenerate: { directory: 'pku' } }],
				},
				{
					label: '3 · Lifestyle',
					items: [{ autogenerate: { directory: 'lifestyle' } }],
				},
				{
					label: 'Everything else',
					collapsed: true,
					items: [{ autogenerate: { directory: 'misc' } }],
				},
			],
			lastUpdated: true,
		}),
	],
});
