// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Served from the root of how-to-fl.github.io, so no `base` path is needed.
// If a custom domain is added later, only `site` changes — nothing else.
export default defineConfig({
	site: 'https://how-to-fl.github.io',
	integrations: [
		starlight({
			title: 'how to FL',
			description:
				'A survival guide for Future Leaders arriving in Beijing. Written by the cohorts, for the cohorts.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/how-to-fl/how-to-fl.github.io' },
			],
			// Every font and icon must be served from our own origin — see CONTRIBUTING.md.
			// Nothing here may reference a CDN, Google Fonts, or raw.githubusercontent.com.
			customCss: ['./src/styles/custom.css'],
			components: {
				// Adds the "last checked" line under every page title.
				PageTitle: './src/components/PageTitle.astro',
			},
			// Autogenerated from the directory, so a contributor who adds a Markdown
			// file gets it in the nav without touching this config.
			// Note: as of Starlight 0.39 `autogenerate` must sit inside `items`.
			sidebar: [
				{ label: 'Start here', items: [{ autogenerate: { directory: 'start' } }] },
				{ label: 'Before you arrive', items: [{ autogenerate: { directory: 'arrival' } }] },
				{ label: 'Money & admin', items: [{ autogenerate: { directory: 'admin' } }] },
				{ label: 'Campus & study', items: [{ autogenerate: { directory: 'campus' } }] },
				{ label: 'Living in Beijing', items: [{ autogenerate: { directory: 'living' } }] },
				{ label: 'Exploring Beijing', items: [{ autogenerate: { directory: 'explore' } }] },
				{ label: 'Apps & essentials', items: [{ autogenerate: { directory: 'apps' } }] },
				{ label: 'Beyond the classroom', items: [{ autogenerate: { directory: 'beyond' } }] },
			],
			lastUpdated: true,
		}),
	],
});
